### GET all persons
GET http://localhost:3001/api/persons

###

### POST valid person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Vaibhav",
  "number": "12345"
}

###

### Missing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "99999"
}

###

### Missing number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Rahul"
}

###

### Duplicate name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "88888"
}